### ISSUE TITLE
CASSCF

### ISSUE THREAD

**Issue by Jroque10** [jaimergp/easymecp#4]
Dear Jaime Rodriguez,

I'm a chemistry PhD student from Portugal. Recently, I tried to use the easymecp package that you wrote. It appears to me that it does not support CASSCF calculations, is that right?
I have tried to run at this level of theory, but unfortunately I always receive the following error:
"something failed...Check gaussian outputs and/or Reportfile."

The gaussian outputs terminate well and the report file only has one line with the date and hour of the calculation.

Moreover, when i keep the input file exactly the same and only change the CASSCF method to HF, then the script runs perfectly well.

Can you tell me something about this?

Best regards,

José Roque

**Comment by jaimergp** [comment]
I didn't test it with other levels of theory, so in that case the energies / gradients are reported with a slightly different format. You'll need a custom parsing function and pass it through the `energy_parser` keyword. See [here](https://github.com/jaimergp/easymecp/blob/master/easymecp/easymecp.py#L917-L941) for some examples.

You can pass a path to `script.py` file that defines a function named `parse_energy` with that exact same API:

```python
# casscf_parser.py

def parse_energy(f, line, fields, default=None):
    """ This is just an example! You'll need to figure out the way to get the CASSCF energy back """
    if len(fields) > 4 and fields[0] == 'CASSCF' and fields[1] == 'Done:':
        return float(fields[4])
    return default
```

This code path is not well-tested so you might find some errors. If you can't figure out how to parse those energies, upload a sample output file with that level of theory and I'll provide that function for you. If you do come up with something, feel free to submit a PR and I'll include it in the main script! Thanks!

**Comment by Jroque10** [comment]
Thank you for the fast reply!
I'm not familiar with python language... and I confess I wasn't sure what I was doing. Anyway here goes what i tried, but failed...

The energy is given in this line:
          ( 1)     EIGENVALUE   -452.4028311    

I tried to change the easymecp.py script manually by adding the following code:

def _parse_energy_CASSCF(f, line, fields, default=None):
    if len(fields) > 3 and fields[2] == '1)' and fields[3] == 'EIGENVALUE':
        return float(fields[3])
    return default

However I kept receiving the same error.
Could you please help me?


Thanks
[Job0_B.log](https://github.com/jaimergp/easymecp/files/5597116/Job0_B.log)

**Comment by jaimergp** [comment]
Almost there! Use this one:

```python
def _parse_energy_CASSCF(f, line, fields, default=None):
    if len(fields) > 3 and fields[1] == '1)' and fields[2] == 'EIGENVALUE':
        return float(fields[3])
    return default
```

`fields` is a list of "words" found in the line. You have four in that line: `(`, `1)`, `EIGENVALUE` and the number. Python lists are 0-indexed, so first element is `fields[0]`, second is `fields[1]` and so on.

Now that you have that new parser, you have to tell easymecp to use it with `! easymecp: energy_parser=CASSCF` at the top of your input file, like [here](https://github.com/jaimergp/easymecp/blob/master/tests/data/C6H5%2B_singlefile/input.gjf#L1).

**Comment by Jroque10** [comment]
Thank you very much. Very instructive explanation and its now solved.

By some reason I could not make it work with the "! easemecp: energy_parser=CASSCF" in the input file, but it worked out by setting it in the command line with:
python easymecp.py -f input.gjf --energy_parser CASSCF

Thanks for the help

**Comment by jaimergp** [comment]
Awesome! Closing the issue then.

**Comment by Jroque10** [comment]
Hello Jaime,

I don't know if you can receive this email from here, but i could not find
your official email address.
I'm running your software and I have a couple of questions, I would very
much appreciate if you could enlighten me here:

What does TDE, TDX and TG mean?

Does any one of these parameters allow the user to reduce the geometric
changes during the optimization process? I don't mind if it takes longer
time and more steps, but I'm using CASSCF and I need to guarantee the
active space remains unchanged. Basically I need a smooth transition
between points.

Thank you in advance,

Best regards,

José Roque

Em qua., 25 de nov. de 2020 às 17:00, Jaime Rodríguez-Guerra <
notifications@github.com> escreveu:

**Comment by jaimergp** [comment]
These are parameters specified in the Fortran program. We [expose them](https://github.com/jaimergp/easymecp/blob/master/easymecp/easymecp.py#L1156-L1169) so it's easier to change, but it's actually nothing to do with EasyMECP; more like the original MECP.f program.

This is all I know about those, sorry!
